sudo: required
language: go
go:
  - "1.10.x"
before_install:
- go get -u github.com/docker/docker/client
- go get -u github.com/docker/docker/api
- go get -u github.com/pebbe/zmq4
- make build

script:
- make test
services:
- docker
